### ISSUE TITLE
missing images?

### ISSUE THREAD

**Issue by gerroon** [zalo/zalo.github.io#10]
Hi

I was browsing through your blog, great stuff but it seems like the pages are either missing images or something is wrong with the page structures. I see white rectangles in the pages but no images there.

thanks

**Comment by zalo** [comment]
You’re missing the best part! The blog is filled with interactive examples.

I’m not sure what could be blocking them...

Make sure you’re using a modern browser and that scripts are enabled (and pop-up blockers are disabled? Though I’ve never had any problems with these before...).

**Comment by gerroon** [comment]
Thanks I will try it in another environment.
